// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "./components/Header/Header";
// import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Appstorys",
//   description: "Generated by create next app",
//   icons: "/favicon.png"
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Header />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", 
});

export const metadata = {
  title: "AppStorys - Better In-App User Experiences",
  description: "Discover AppStorys, a SaaS platform that boosts app engagement with stories, PiP videos, banners, and more. Drive growth seamlessly with interactive tools.",
  icons: {
    icon: "/favicon.ico",
    // apple: "/apple-icon.png", 
    // shortcut: "/favicon.png",
  },
  metadataBase: new URL("https://appstorys.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "AppStorys - Better In-App User Experiences",
    description: "Discover AppStorys, a SaaS platform that boosts app engagement with stories, PiP videos, banners, and more.",
    url: "https://appstorys.com",
    siteName: "AppStorys",
    images: [
      {
        url: "/og-image.jpg", // Create this OG image (1200x630)
        width: 1200,
        height: 630,
        alt: "AppStorys Platform",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AppStorys - Better In-App User Experiences",
    description: "Discover AppStorys, a SaaS platform that boosts app engagement with stories, PiP videos, banners, and more.",
    images: ["/twitter-image.jpg"], 
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  keywords: "app engagement, in-app stories, PiP videos, user retention, app growth, mobile engagement, interactive content",
  authors: [{ name: "AppStorys Team" }],
  publisher: "AppStorys",
  viewport: "width=device-width, initial-scale=1",
  themeColor: "#4f46e5", 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          id="schema-software-application"
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              "name": "AppStorys",
              "applicationCategory": "BusinessApplication",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD"
              },
              "description": "A SaaS platform that boosts app engagement with stories, PiP videos, banners, and more.",
              "operatingSystem": "Web",
              "aggregateRating": {
                "@type": "AggregateRating",
                "ratingValue": "4.8",
                "ratingCount": "1024"
              }
            })
          }}
        />
        <Script
          id="google-analytics"   
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XXXXXXXXXX'); // Replace with your Google Analytics ID
            `,
          }}
        />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}