# .github/workflows/deploy.yml
name: Build & Deploy to EC2

on:
  push:
    branches:
      - main       
jobs:
  build-and-deploy:
    name: Build, Export & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build and export Next.js
        run: |
          npm run build
          npm run export

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Clean remote directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "rm -rf /var/www/appstorys/*"

      - name: Deploy exported static files to EC2
        run: |
          rsync -avz \
            -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
            out/ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/myapp/
